### ISSUE TITLE
好像资源不是很多，100多本书吧？

### ISSUE THREAD

**Issue by ghost** [guapier/zi5book#3]
可否发一份爬取结果用于研究？邮箱 zmrenwu@163.com

**Comment by guapier** [comment]
正常来说是可以下载600本左右的，你可以把访问频率调低一点，我这边下班之前下载了500本左右

**Comment by guapier** [comment]
@zmrenwu

**Comment by ghost** [comment]
我在虚拟机 Ubuntu 18.04 启动爬虫报错：

ping book.zi5.me 是通的。是不是爬虫失效了？
```
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/35> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/36> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/24> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/37> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/24>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/30> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/38> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/30>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/39> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/40> (failed 2 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/32> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/32>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/33> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/35> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/36> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:04 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/33>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/35>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/36>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://book.zi5.me/page/37> (referer: None)
2019-02-25 06:57:05 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/42> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/38> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/38>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/39> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/39>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.downloadermiddlewares.retry] DEBUG: Gave up retrying <GET http://book.zi5.me/page/40> (failed 3 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:05 [scrapy.core.scraper] ERROR: Error downloading <GET http://book.zi5.me/page/40>
Traceback (most recent call last):
  File "/home/zmrenwu/.local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/43> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/41> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/44> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/46> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/45> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/page/47> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/336> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/337> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/338> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/339> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:06 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/340> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:07 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/343> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:07 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/335> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:07 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/345> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:07 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/346> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:07 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/348> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:08 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/349> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
2019-02-25 06:57:08 [scrapy.downloadermiddlewares.retry] DEBUG: Retrying <GET http://book.zi5.me/archives/book/350> (failed 1 times): [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion.>]
```

**Comment by guapier** [comment]
@zmrenwu 已经修复了，你可以重新试试
